# ...
remote_theme: just-the-docs/just-the-docs

# Just the Docs options
# logo: /assets/images/logo.png
color_scheme: light
search_enabled: true
enable_copy_code_button: true

aux_links:
  "CCMS Hub on GitHub":
    - "https://github.com/mfuadj/ccms-docs"

footer_content: "© 2025 CCMS Hub"

collections:
  docs:
    output: true
    permalink: /:collection/:path/

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
  version_label: "v1"

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
