title: CCMS Hub
description: Clinical Care Management System Documentation
baseurl: "/ccms-docs"
url: "https://mfuadj.github.io"

remote_theme: just-the-docs/just-the-docs

# Branding
# logo: /assets/images/logo.png
color_scheme: ccms
search_enabled: true
enable_copy_code_button: true
footer_content: "© 2025 CCMS Hub"

# Header links
aux_links:
  "CCMS Hub on GitHub":
    - "https://github.com/mfuadj/ccms-docs"

# Docs collection
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Just the Docs options
just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
  version_label: "v1"
  gh_edit_link: true
  gh_edit_link_text: "Edit this page on GitHub"
  gh_edit_repository: "https://github.com/mfuadj/ccms-docs"
  gh_edit_branch: "main"
  gh_edit_view_mode: "edit"
  last_edit_timestamp: true
  last_edit_time_format: "%b %e, %Y"

# Build
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
